apiVersion: v1
kind: Service
metadata:
  name: webserver 
spec:
  selector:
    app: {{ .Values.deployment.name }} 
  ports:
  - port: {{ .Values.service.port }} 
    targetPort: {{ .Values.service.port }}